<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?= $this->headTitle('AddressBook')->setSeparator(' - ') ?>
    
    <?= $this->headMeta() ?>
    
    <link href="<?= $this->baseUrl('bower_components/bootstrap/dist/css/bootstrap.css') ?>" rel="stylesheet">
    
    <?= $this->headLink() ?>
    
    <?= $this->headStyle() ?>
    
    <?= $this->headScript() ?>
    
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<?= $this->rurl([]) ?>">AddressBook</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li<?=$this->classActive([])?>>
                <a href="<?= $this->rurl([]) ?>">Home</a>
            </li>
            <li<?=$this->classActive(['controller' => 'contact'])?>>
                <a href="<?= $this->rurl(['controller' => 'contact']) ?>">Contacts</a>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <h2><?= $this->placeholder('h2') ?></h2>
        
      <?php echo $this->layout()->content; ?>

    </div><!-- /.container -->


    <script src="<?= $this->baseUrl('bower_components/jquery/dist/jquery.js') ?>"></script>
    <script src="<?= $this->baseUrl('bower_components/bootstrap/dist/js/bootstrap.js') ?>"></script>
    
    <?= $this->inlineScript() ?>
  </body>
</html>
